name: CI

on:
  pull_request:
    branches:
      - main
      - develop
    types: [opened, ready_for_review, reopened, synchronize]

jobs:
  sonar_build:
    name: SonarCloud Lint
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_ACCESS_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew build sonarqube --info

  frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout 2022-kkogkkog repository
        uses: actions/checkout@v3
      - name: Setup Node.js on runner
        uses: actions/setup-node@v2
        with:
          node-version: "16.1.0"
      - name: Install yarn dependencies
        run: yarn
      - name: yarn build
        run: yarn build

  backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout 2022-kkogkkog repository
        uses: actions/checkout@v3
      - name: Set up JDK 11 on runner
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Test & Build with gradle
        run: ./gradlew build
