name: CI

on:
  pull_request:
    branches:
      - main
      - develop
    types: [opened, ready_for_review, reopened, synchronize]

jobs:
  frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout 2022-kkogkkog repository
        uses: actions/checkout@v3
      - name: Setup Node.js on runner
        uses: actions/setup-node@v2
        with:
          node-version: "16.1.0"
      - name: Install yarn dependencies
        run: yarn
      - name: yarn build
        run: yarn build

  backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout 2022-kkogkkog repository
        uses: actions/checkout@v3
      - name: Set up JDK 11 on runner
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Test & Build with gradle
        run: ./gradlew build
